const DATA = {
  short: {
    vibeId: "Late Night Explorer",
    vibeDesc: "High energy, emotionally complex music with a taste for deep cuts. You discover artists before they're mainstream.",
    hours: 847, tracks: 1204, artists: 312, streak: 47,
    audioFeatures: [
      { label: "Energy", val: 0.82, color: "#1db954" },
      { label: "Danceability", val: 0.67, color: "#f5a623" },
      { label: "Valence", val: 0.44, color: "#e8445a" },
      { label: "Acousticness", val: 0.21, color: "#5b9cf6" },
      { label: "Instrumentalness", val: 0.38, color: "#a78bfa" },
    ],
    tracks: [
      { emoji: "🎵", name: "Blinding Lights", artist: "The Weeknd", duration: "3:20", pop: 0.97 },
      { emoji: "🎸", name: "As It Was", artist: "Harry Styles", duration: "2:47", pop: 0.95 },
      { emoji: "🔥", name: "Flowers", artist: "Miley Cyrus", duration: "3:21", pop: 0.93 },
      { emoji: "💜", name: "Cruel Summer", artist: "Taylor Swift", duration: "2:58", pop: 0.91 },
      { emoji: "🌙", name: "Levitating", artist: "Dua Lipa", duration: "3:23", pop: 0.88 },
      { emoji: "⚡", name: "Bad Guy", artist: "Billie Eilish", duration: "3:14", pop: 0.86 },
      { emoji: "🎤", name: "Watermelon Sugar", artist: "Harry Styles", duration: "2:54", pop: 0.84 },
      { emoji: "🌊", name: "Peaches", artist: "Justin Bieber", duration: "3:18", pop: 0.82 },
      { emoji: "🔮", name: "Industry Baby", artist: "Lil Nas X", duration: "3:32", pop: 0.80 },
      { emoji: "🎹", name: "Heat Waves", artist: "Glass Animals", duration: "3:59", pop: 0.78 },
    ],
    artists: [
      { emoji: "🌙", name: "The Weeknd", genre: "R&B / Pop", rank: "#1" },
      { emoji: "💫", name: "Taylor Swift", genre: "Pop", rank: "#2" },
      { emoji: "🎸", name: "Harry Styles", genre: "Pop Rock", rank: "#3" },
      { emoji: "💃", name: "Dua Lipa", genre: "Dance Pop", rank: "#4" },
      { emoji: "🌿", name: "Billie Eilish", genre: "Alt Pop", rank: "#5" },
      { emoji: "🔊", name: "Drake", genre: "Hip-Hop", rank: "#6" },
      { emoji: "⚡", name: "Kendrick Lamar", genre: "Hip-Hop", rank: "#7" },
      { emoji: "🎹", name: "Glass Animals", genre: "Indie Pop", rank: "#8" },
    ],
    genres: [
      { name: "Pop", pct: 34, color: "#1db954" },
      { name: "Hip-Hop / Rap", pct: 22, color: "#f5a623" },
      { name: "Indie / Alt", pct: 18, color: "#5b9cf6" },
      { name: "R&B / Soul", pct: 14, color: "#e8445a" },
      { name: "Electronic", pct: 7, color: "#a78bfa" },
      { name: "Rock", pct: 5, color: "#fb923c" },
    ],
    radar: [0.82, 0.67, 0.44, 0.21, 0.38, 0.61],
    recent: [
      { emoji: "🎵", name: "Blinding Lights", artist: "The Weeknd", time: "2m ago" },
      { emoji: "💜", name: "Cruel Summer", artist: "Taylor Swift", time: "18m ago" },
      { emoji: "🌊", name: "Levitating", artist: "Dua Lipa", time: "24m ago" },
      { emoji: "🔥", name: "Flowers", artist: "Miley Cyrus", time: "31m ago" },
      { emoji: "⚡", name: "Bad Guy", artist: "Billie Eilish", time: "38m ago" },
      { emoji: "🎸", name: "As It Was", artist: "Harry Styles", time: "44m ago" },
      { emoji: "🔮", name: "Industry Baby", artist: "Lil Nas X", time: "52m ago" },
      { emoji: "🎹", name: "Heat Waves", artist: "Glass Animals", time: "1h ago" },
    ]
  },
  medium: {
    vibeId: "Eclectic Archivist",
    vibeDesc: "You cycle through phases — indie one week, rap the next. Your library is vast and your taste is genuinely hard to pin down.",
    hours: 2340, tracks: 3891, artists: 782, streak: 47,
    audioFeatures: [
      { label: "Energy", val: 0.71, color: "#1db954" },
      { label: "Danceability", val: 0.75, color: "#f5a623" },
      { label: "Valence", val: 0.56, color: "#e8445a" },
      { label: "Acousticness", val: 0.33, color: "#5b9cf6" },
      { label: "Instrumentalness", val: 0.29, color: "#a78bfa" },
    ],
    tracks: [
      { emoji: "🎤", name: "Rich Flex", artist: "Drake & 21 Savage", duration: "4:03", pop: 0.94 },
      { emoji: "🌿", name: "Ghost in the Machine", artist: "SZA ft. Phoebe", duration: "3:52", pop: 0.88 },
      { emoji: "💀", name: "All the Stars", artist: "Kendrick Lamar", duration: "3:52", pop: 0.90 },
      { emoji: "🔊", name: "Easy On Me", artist: "Adele", duration: "3:44", pop: 0.93 },
      { emoji: "🌙", name: "Save Your Tears", artist: "The Weeknd", duration: "3:35", pop: 0.91 },
      { emoji: "🎸", name: "drivers license", artist: "Olivia Rodrigo", duration: "4:02", pop: 0.89 },
      { emoji: "🌊", name: "good 4 u", artist: "Olivia Rodrigo", duration: "2:58", pop: 0.87 },
      { emoji: "🔮", name: "Montero", artist: "Lil Nas X", duration: "2:17", pop: 0.85 },
      { emoji: "⚡", name: "Arcade", artist: "Duncan Laurence", duration: "3:37", pop: 0.78 },
      { emoji: "🎹", name: "Midnight Rain", artist: "Taylor Swift", duration: "5:42", pop: 0.82 },
    ],
    artists: [
      { emoji: "💀", name: "Kendrick Lamar", genre: "Hip-Hop", rank: "#1" },
      { emoji: "🌿", name: "SZA", genre: "R&B", rank: "#2" },
      { emoji: "🎤", name: "Drake", genre: "Hip-Hop", rank: "#3" },
      { emoji: "🌙", name: "The Weeknd", genre: "R&B / Pop", rank: "#4" },
      { emoji: "🎸", name: "Olivia Rodrigo", genre: "Pop Rock", rank: "#5" },
      { emoji: "🔊", name: "Adele", genre: "Soul / Pop", rank: "#6" },
      { emoji: "💃", name: "Dua Lipa", genre: "Dance Pop", rank: "#7" },
      { emoji: "🎹", name: "Taylor Swift", genre: "Pop", rank: "#8" },
    ],
    genres: [
      { name: "Hip-Hop / Rap", pct: 31, color: "#f5a623" },
      { name: "Pop", pct: 26, color: "#1db954" },
      { name: "R&B / Soul", pct: 20, color: "#e8445a" },
      { name: "Indie / Alt", pct: 13, color: "#5b9cf6" },
      { name: "Electronic", pct: 6, color: "#a78bfa" },
      { name: "Other", pct: 4, color: "#fb923c" },
    ],
    radar: [0.71, 0.75, 0.56, 0.33, 0.29, 0.55],
    recent: [
      { emoji: "🎤", name: "Rich Flex", artist: "Drake & 21 Savage", time: "5m ago" },
      { emoji: "💀", name: "All the Stars", artist: "Kendrick Lamar", time: "12m ago" },
      { emoji: "🌿", name: "Ghost in Machine", artist: "SZA", time: "19m ago" },
      { emoji: "🔊", name: "Easy On Me", artist: "Adele", time: "26m ago" },
      { emoji: "🌙", name: "Save Your Tears", artist: "The Weeknd", time: "33m ago" },
      { emoji: "🎸", name: "drivers license", artist: "Olivia Rodrigo", time: "41m ago" },
      { emoji: "🌊", name: "good 4 u", artist: "Olivia Rodrigo", time: "49m ago" },
      { emoji: "🔮", name: "Montero", artist: "Lil Nas X", time: "57m ago" },
    ]
  },
  long: {
    vibeId: "Sonic Archaeologist",
    vibeDesc: "Thousands of hours across years, genres, eras. You don't just listen to music — you live inside it. Few can match the depth of your archive.",
    hours: 9412, tracks: 11820, artists: 2403, streak: 47,
    audioFeatures: [
      { label: "Energy", val: 0.65, color: "#1db954" },
      { label: "Danceability", val: 0.61, color: "#f5a623" },
      { label: "Valence", val: 0.52, color: "#e8445a" },
      { label: "Acousticness", val: 0.48, color: "#5b9cf6" },
      { label: "Instrumentalness", val: 0.44, color: "#a78bfa" },
    ],
    tracks: [
      { emoji: "🌙", name: "Thriller", artist: "Michael Jackson", duration: "5:57", pop: 0.96 },
      { emoji: "⚡", name: "Bohemian Rhapsody", artist: "Queen", duration: "5:55", pop: 0.95 },
      { emoji: "🎸", name: "Hotel California", artist: "Eagles", duration: "6:30", pop: 0.92 },
      { emoji: "🎤", name: "Lose Yourself", artist: "Eminem", duration: "5:26", pop: 0.90 },
      { emoji: "💫", name: "Billie Jean", artist: "Michael Jackson", duration: "4:54", pop: 0.93 },
      { emoji: "🔥", name: "Purple Rain", artist: "Prince", duration: "8:41", pop: 0.88 },
      { emoji: "🌊", name: "Smells Like Teen Spirit", artist: "Nirvana", duration: "5:01", pop: 0.91 },
      { emoji: "🎹", name: "Stairway to Heaven", artist: "Led Zeppelin", duration: "8:02", pop: 0.89 },
      { emoji: "🔮", name: "Mr. Brightside", artist: "The Killers", duration: "3:42", pop: 0.87 },
      { emoji: "💜", name: "Africa", artist: "Toto", duration: "4:55", pop: 0.85 },
    ],
    artists: [
      { emoji: "🌙", name: "Michael Jackson", genre: "Pop / R&B", rank: "#1" },
      { emoji: "⚡", name: "Queen", genre: "Rock", rank: "#2" },
      { emoji: "🎸", name: "Led Zeppelin", genre: "Hard Rock", rank: "#3" },
      { emoji: "🎹", name: "The Beatles", genre: "Classic Rock", rank: "#4" },
      { emoji: "🔥", name: "Prince", genre: "Funk / Pop", rank: "#5" },
      { emoji: "🌊", name: "Nirvana", genre: "Grunge", rank: "#6" },
      { emoji: "🎤", name: "Eminem", genre: "Hip-Hop", rank: "#7" },
      { emoji: "💫", name: "David Bowie", genre: "Art Rock", rank: "#8" },
    ],
    genres: [
      { name: "Classic Rock", pct: 28, color: "#fb923c" },
      { name: "Pop", pct: 22, color: "#1db954" },
      { name: "Hip-Hop / Rap", pct: 17, color: "#f5a623" },
      { name: "R&B / Soul", pct: 14, color: "#e8445a" },
      { name: "Indie / Alt", pct: 11, color: "#5b9cf6" },
      { name: "Electronic", pct: 8, color: "#a78bfa" },
    ],
    radar: [0.65, 0.61, 0.52, 0.48, 0.44, 0.58],
    recent: [
      { emoji: "🌙", name: "Thriller", artist: "Michael Jackson", time: "1h ago" },
      { emoji: "⚡", name: "Bohemian Rhapsody", artist: "Queen", time: "1h ago" },
      { emoji: "🎸", name: "Hotel California", artist: "Eagles", time: "2h ago" },
      { emoji: "🎤", name: "Lose Yourself", artist: "Eminem", time: "2h ago" },
      { emoji: "💫", name: "Billie Jean", artist: "Michael Jackson", time: "3h ago" },
      { emoji: "🔥", name: "Purple Rain", artist: "Prince", time: "3h ago" },
      { emoji: "🌊", name: "Smells Like Teen Spirit", artist: "Nirvana", time: "4h ago" },
      { emoji: "🎹", name: "Stairway to Heaven", artist: "Led Zeppelin", time: "4h ago" },
    ]
  }
};
